In [3]:
import pandas as pd

df = pd.read_csv("./Car_Dataset_Processed.csv")

df.columns

Index(['Unnamed: 0', 'car_name', 'registration_year', 'insurance_validity',
       'fuel_type', 'seats', 'kms_driven', 'ownsership', 'transmission',
       'manufacturing_year', 'mileage(kmpl)', 'engine(cc)', 'max_power(bhp)',
       'torque(Nm)', 'price(in lakhs)'],
      dtype='str')

In [4]:
df['fuel_type'].value_counts()

fuel_type
Petrol    997
Diesel    480
CNG        22
Name: count, dtype: int64

In [5]:
d1 = {'Petrol':0, 'Diesel': 1, 'CNG': 2}
df['fuel_type'] = df['fuel_type'].map(d1)

In [6]:
df['fuel_type'].value_counts()

fuel_type
0    997
1    480
2     22
Name: count, dtype: int64

In [7]:
df['ownsership'].value_counts()

ownsership
First Owner     1236
Second Owner     240
Third Owner       21
Fifth Owner        2
Name: count, dtype: int64

In [8]:
df['insurance_validity'].value_counts()

insurance_validity
Comprehensive            1081
Third Party insurance     289
Zero Dep                   64
Third Party                63
Not Available               2
Name: count, dtype: int64

In [9]:
d2 = {'Comprehensive': 0, 'Third Party insurance':1, 'Zero Dep': 2, 'Third Party': 1, 'Not Available':3 }
df['insurance_validity'] = df['insurance_validity'].map(d2)

In [10]:
d3 = {'First Owner': 1, 'Second Owner':2, 'Third Owner': 3, 'Fifth Owner': 5, 'Fourth Owner': 4 }
df['ownsership'] = df['ownsership'].map(d3)

In [11]:
df['ownsership'].value_counts()

ownsership
1    1236
2     240
3      21
5       2
Name: count, dtype: int64

In [12]:
df['transmission'].value_counts()

transmission
Manual       832
Automatic    667
Name: count, dtype: int64

In [13]:
d4 = {'Manual': 0, 'Automatic':1 }
df['transmission'] = df['transmission'].map(d4)

In [14]:
df['transmission'].value_counts()

transmission
0    832
1    667
Name: count, dtype: int64

In [15]:
df.head()

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,0,0,5,56000,1,1,2017,7.81,2996.0,2996.0,333.0,63.75
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,0,0,5,30615,1,1,2020,17.40,999.0,999.0,9863.0,8.99
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,0,1,5,24000,1,1,2018,20.68,1995.0,1995.0,188.0,23.75
3,3,2019 Kia Seltos GTX Plus,Dec-19,0,0,5,18378,1,0,2019,16.50,1353.0,1353.0,13808.0,13.56
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,0,0,5,44900,1,1,2019,14.67,1798.0,1798.0,17746.0,24.00

In [16]:
df['registration_year']

0       Jul-17
1       Jan-21
2       Sep-18
3       Dec-19
4       Aug-19
         ...
1494    May-22
1495    Aug-20
1496    Jun-17
1497    May-18
1498    May-18
Name: registration_year, Length: 1499, dtype: str

In [17]:
df['registration_year'] = df['registration_year'].apply(lambda x: str(x)[-2:])
print(df['registration_year'].head())

0    17
1    21
2    18
3    19
4    19
Name: registration_year, dtype: str

In [18]:
X = df[['insurance_validity', 'fuel_type', 'kms_driven', 'ownsership', 'transmission']]
Y = df['price(in lakhs)']

X.head()

   insurance_validity  fuel_type  kms_driven  ownsership  transmission
0                   0          0       56000           1             1
1                   0          0       30615           1             1
2                   0          1       24000           1             1
3                   0          0       18378           1             0
4                   0          0       44900           1             1

In [19]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR

In [20]:
models = {'LinReg': LinearRegression(), 'KNN-3': KNeighborsRegressor(n_neighbors=3), 'SVM-Poly': SVR(kernel='poly')}

for name,model in models.items():
  model.fit(X,Y)
  sc = model.score(X,Y)
  print(name, sc)

LinReg 0.01881841973825704
KNN-3 0.5927605118086187
SVM-Poly -0.002159341825328953

In [21]:
final_model = models['KNN-3']

In [22]:
insurance_validity = input("enter insurance validity: ")
fuel_type = input("enter fuel type: ")
kms_driven = input("enter kms driven:")
ownsership = input("enter ownsership: ")
transmission = input("enter transmission: ")

insurance_validity = d2[insurance_validity]
fuel_type = d1[fuel_type]
ownsership = d3[ownsership]
transmission = d4[transmission]

kms_driven = int(kms_driven)

test = [[insurance_validity, fuel_type, kms_driven, ownsership, transmission]]
yp  = int(final_model.predict(test)[0])
print("Predicted Price of the car is {} Rs.", format(yp))

Predicted Price of the car is {} Rs. 48

c:\Users\aadit\Downloads\MIT_CAR_APP\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(

In [23]:
linear_model = models['LinReg']

In [24]:
insurance_validity = input("enter insurance validity: ")
fuel_type = input("enter fuel type: ")
kms_driven = input("enter kms driven:")
ownsership = input("enter ownsership: ")
transmission = input("enter transmission: ")

insurance_validity = d2[insurance_validity]
fuel_type = d1[fuel_type]
ownsership = d3[ownsership]
transmission = d4[transmission]

kms_driven = int(kms_driven)

test = [[insurance_validity, fuel_type, kms_driven, ownsership, transmission]]
yp  = int(final_model.predict(test)[0])
print(f"Predicted Price of the car is {yp} Rs")

KeyError: ''